setup-gitHub-ctions
atlp-rwanda/atlp-apprenticeship-bn pull request #5
Opened 2023-08-18 06:27 UTC by NTElissa

As a developer, I want to setup continuous integration using GitHub Actions.

2023-08-18 14:22 UTC, Virgile1k approved these changes
Checked

2023-08-18 14:47 UTC, NdatimanaSamuel approved these changes

2023-08-18 15:33 UTC, ceelogre requested changes

2023-08-18 15:33 UTC, ceelogre commented on .github/workflows/action.yml
> +    branches: [ "main" ]
Should only run on PRs against develop.

2023-08-21 07:34 UTC, Lydie260 approved these changes

2023-08-21 19:15 UTC, ceelogre requested changes
This comment hasn't been addressed. https://github.com/atlp-rwanda/atlp-apprenticeship-bn/pull/5/files#r1298591053

2023-08-24 07:30 UTC, rukundo-kevin approved these changes

2023-08-24 13:09 UTC, ceelogre approved these changes

2023-08-24 13:10 UTC, merged