setting up docker for backend
atlp-rwanda/atlp-apprenticeship-bn pull request #9
Opened 2023-08-22 15:25 UTC by Muhet

2023-08-23 13:43 UTC, ceelogre requested changes

2023-08-23 13:43 UTC, ceelogre commented on Dockerfile
> +FROM node:slim
What's the difference between slim and latest?

2023-08-23 13:43 UTC, ceelogre commented on Dockerfile
> +RUN npm install
How comes there is no build step?

2023-08-25 06:41 UTC, rukundo-kevin approved these changes

2023-08-28 07:40 UTC, Virgile1k approved these changes
Checked and approved

2023-08-28 07:46 UTC, Lydie260 approved these changes

2023-08-28 09:44 UTC, NTElissa approved these changes

2023-08-28 10:22 UTC, NTElissa approved these changes

2023-08-29 13:29 UTC, ceelogre requested changes
Merging develop into your feature branch is not accepted. Please reset this commit.
![image](https://github.com/atlp-rwanda/atlp-apprenticeship-bn/assets/5022823/aad6813c-803a-4e41-acde-d0451c265dbd)

2023-08-30 12:32 UTC, closed without merging